# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/midou/git_rep/SDL_Gravity_Box

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/midou/git_rep/SDL_Gravity_Box

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/midou/git_rep/SDL_Gravity_Box/CMakeFiles /home/midou/git_rep/SDL_Gravity_Box//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/midou/git_rep/SDL_Gravity_Box/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SDL_Gravity_Box

# Build rule for target.
SDL_Gravity_Box: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL_Gravity_Box
.PHONY : SDL_Gravity_Box

# fast build rule for target.
SDL_Gravity_Box/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/build
.PHONY : SDL_Gravity_Box/fast

src/entity.o: src/entity.cpp.o
.PHONY : src/entity.o

# target to build an object file
src/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/entity.cpp.o
.PHONY : src/entity.cpp.o

src/entity.i: src/entity.cpp.i
.PHONY : src/entity.i

# target to preprocess a source file
src/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/entity.cpp.i
.PHONY : src/entity.cpp.i

src/entity.s: src/entity.cpp.s
.PHONY : src/entity.s

# target to generate assembly for a file
src/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/entity.cpp.s
.PHONY : src/entity.cpp.s

src/input.o: src/input.cpp.o
.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/math.o: src/math.cpp.o
.PHONY : src/math.o

# target to build an object file
src/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/math.cpp.o
.PHONY : src/math.cpp.o

src/math.i: src/math.cpp.i
.PHONY : src/math.i

# target to preprocess a source file
src/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/math.cpp.i
.PHONY : src/math.cpp.i

src/math.s: src/math.cpp.s
.PHONY : src/math.s

# target to generate assembly for a file
src/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/math.cpp.s
.PHONY : src/math.cpp.s

src/mplayer.o: src/mplayer.cpp.o
.PHONY : src/mplayer.o

# target to build an object file
src/mplayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/mplayer.cpp.o
.PHONY : src/mplayer.cpp.o

src/mplayer.i: src/mplayer.cpp.i
.PHONY : src/mplayer.i

# target to preprocess a source file
src/mplayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/mplayer.cpp.i
.PHONY : src/mplayer.cpp.i

src/mplayer.s: src/mplayer.cpp.s
.PHONY : src/mplayer.s

# target to generate assembly for a file
src/mplayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/mplayer.cpp.s
.PHONY : src/mplayer.cpp.s

src/renderwindow.o: src/renderwindow.cpp.o
.PHONY : src/renderwindow.o

# target to build an object file
src/renderwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/renderwindow.cpp.o
.PHONY : src/renderwindow.cpp.o

src/renderwindow.i: src/renderwindow.cpp.i
.PHONY : src/renderwindow.i

# target to preprocess a source file
src/renderwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/renderwindow.cpp.i
.PHONY : src/renderwindow.cpp.i

src/renderwindow.s: src/renderwindow.cpp.s
.PHONY : src/renderwindow.s

# target to generate assembly for a file
src/renderwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_Gravity_Box.dir/build.make CMakeFiles/SDL_Gravity_Box.dir/src/renderwindow.cpp.s
.PHONY : src/renderwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SDL_Gravity_Box"
	@echo "... src/entity.o"
	@echo "... src/entity.i"
	@echo "... src/entity.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/math.o"
	@echo "... src/math.i"
	@echo "... src/math.s"
	@echo "... src/mplayer.o"
	@echo "... src/mplayer.i"
	@echo "... src/mplayer.s"
	@echo "... src/renderwindow.o"
	@echo "... src/renderwindow.i"
	@echo "... src/renderwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

